version: '3.9'


services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=greetdb
            - POSTGRES_USER=greetroot
            - POSTGRES_PASSWORD=greetpass
        ports:
            - "5432:5432"


    app:
        container_name: socialweb
        build: .
        volumes:
        - ./:/socialweb
        ports:
        - 8000:8000
        env_file:
        - .env.dev
        environment:
        - DJANGO_SETTINGS_MODULE=settings.dev_settings
        command: >
             sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate  &&
             python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db


volumes:
        postgresql-data:
