version: '3.9'


services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=greetingdata
            - POSTGRES_USER=greetinguser
            - POSTGRES_PASSWORD=greetingpassword


    app:
        container_name: socialweb
        build: .
        volumes:
        - ./:/socialweb
        ports:
        - 8000:8000
        env_file:
        - .env.dev
        environment:
        - NAME=greetingdata
        - USER=greetinguser
        - PASSWORD=greetingpassword
        - HOST=db
        - DJANGO_SETTINGS_MODULE=settings.dev_settings
        command: >
             sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db


volumes:
        postgresql-data:
